version: 3

tasks:
  isort:
    cmds:
      - which python3
      - isort json_schema_filter/ test/
  flake8:
    cmd: flake8 json_schema_filter/ test/
  black:
    cmds:
      - which python3 
      - black json_schema_filter/
  build:
    cmd: poetry build
  publish:
    cmd: poetry publish
  test:
    cmd: pytest test/ --cov=json_schema_filter/
  